# Generated by Django 5.0.2 on 2024-02-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number_of_games',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number_of_games_won',
        ),
    ]
