# Generated by Django 5.0.2 on 2024-02-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pool_game',
            new_name='Game',
        ),
    ]
