# Generated by Django 5.0.2 on 2024-03-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
