# Generated by Django 5.0.2 on 2024-02-16 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_rename_pool_game_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 19, 30, 25, 354115, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
