# Generated by Django 5.0.2 on 2024-02-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_game_game_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='games_played',
            new_name='number_of_games',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='games_won',
            new_name='number_of_games_won',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_2',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games_played', to='pool.player'),
        ),
    ]
